
// -------------- POPULATE DB ---------------

// populates db with dummy data
POST localhost:7070/api/instructor/populate

// -------------- Skiing Routes ROUTES - CRUDS ---------------

// add an exisiting instructor by id to existing course by id
###
PUT localhost:7070/api/courses/1/instructors/2



// -------------- INSTRUCTOR ROUTES - CRUDS ---------------

// get all instructors
###
GET localhost:7070/api/instructor/all

// get instructor by id
###
GET localhost:7070/api/instructor/2

// create instructor
###
POST localhost:7070/api/instructor
Content-Type: "application/json"

{
  "firstName": "Wonder",
  "lastName": "Woman",
  "email": "wonderwoman@marvel.com",
  "phone": "12121212",
  "yearsOfExperience": 52
}


// update doctor
###
PUT localhost:7070/api/instructor/2

{
  "firstName": "hulk",
  "lastName": "testing new name",
  "email": "hulk@marvel.com",
  "phone": "11111111",
  "yearsOfExperience": 20
}

// delete doctor
###
DELETE localhost:7070/api/instructor/1

// -------------- EXTERNAL API ROUTES -  ---------------

// search skiing courses by level
###
GET localhost:7070/api/courses/search/Beginner

// get total duration of skiing lessons - search by level
###
GET localhost:7070/api/courses/search/duration/beginner

// -------------- STREAMS ROUTES -  ---------------

// search courses by instructor id -
###
GET localhost:7070/api/courses/search/instructor/1


